--
-- Unit Test SQL*Loader Control File
--
-- sqlldr username/password CONTROL=FILENAME
--
load data infile *
into table GLOBAL_PARMS append
   when key = 'GLOBAL_PARMS                  '
   fields terminated by ''
   trailing nullcols
      (key FILLER position(1:31)
      ,global_set        CHAR(1)
      ,db_constraints    CHAR(1)
      ,fold_strings      CHAR(1)
      ,ignore_no_change  CHAR(1)
      ,description       CHAR(2000) )
into table PARM_SETS append
   when key = 'PARM_SETS                     '
   fields terminated by ''
   trailing nullcols
      (key FILLER   position(1:31)
      ,parm_set     CHAR(30)
      ,description  CHAR(2000) )
into table TEST_PARMS append
   when key = 'TEST_PARMS                    '
   fields terminated by ''
   trailing nullcols
      (key FILLER   position(1:31)
      ,parm_set     CHAR(30)
      ,parm_seq     FLOAT EXTERNAL
      ,result_txt   CHAR(4000)
      ,val0         CHAR(4000)
      ,val1         CHAR(4000)
      ,val2         CHAR(4000)
      ,val3         CHAR(4000)
      ,val4         CHAR(4000)
      ,val5         CHAR(4000)
      ,val6         CHAR(4000)
      ,val7         CHAR(4000)
      ,val8         CHAR(4000)
      ,val9         CHAR(4000)
      ,description  CHAR(2000) )
into table TEST_SETS append
   when key = 'TEST_SETS                     '
   fields terminated by ''
   trailing nullcols
      (key FILLER position(1:31)
      ,user_name    CHAR(30)
      ,global_set   CHAR(1)
      ,test_name    CHAR(30)
      ,parm_set     CHAR(30)
      ,description  CHAR(2000) )
BEGINDATA
GLOBAL_PARMS                  ATTT
GLOBAL_PARMS                  BTTF
GLOBAL_PARMS                  CTFT
GLOBAL_PARMS                  DTFF
GLOBAL_PARMS                  EFTT
GLOBAL_PARMS                  FFTF
GLOBAL_PARMS                  GFFT
GLOBAL_PARMS                  HFFF
PARM_SETS                     BTT_NUM_PASSHappy Path Basic Table Test (DTC, POPT, Partial HAT, Partial APIT, and Partial DMLIT) for Plain Numbers
PARM_SETS                     BTT_NUM_LOG_NoIntDBFailed Basic Table Test for SQL LOG Table Insert with no Integrity (Triggers) at Database Server
PARM_SETS                     BTT_NUM_EFF_NoIntDBFailed Basic Table Test for SQL EFF Table Insert with no Integrity (Triggers) at Database Server
PARM_SETS                     BTT_NUM_NoPerm_INSFailed Basic Table Test for SQL LOG/EFF Tables Insert with unknown missing permission at Mid-Tier Serverber
PARM_SETS                     BTT_NUM_USR_NULL_INSFailed Basic Table Test for SQL LOG/EFF ACT Views Insert DB_CONSTRAINTS = TRUE and no Integrity (Triggers)
TEST_PARMS                    BTT_NUM_PASS1SUCCESS11456.78
TEST_PARMS                    BTT_NUM_PASS2SUCCESS12123.89-5.6e-70
TEST_PARMS                    BTT_NUM_PASS3SUCCESS13-1.2e-403.4e50
TEST_PARMS                    BTT_NUM_PASS4SUCCESS141.2e50
TEST_PARMS                    BTT_NUM_LOG_NoIntDB1FAILURE at UPDATE: ORA-20000: t1a_log_aud row_cnt is not 1:%1123.89-5.6e-70
TEST_PARMS                    BTT_NUM_EFF_NoIntDB1FAILURE at UPDATE: ORA-20000: t1a_eff_hist row_cnt is not 1:%1123.89-5.6e-70
TEST_PARMS                    BTT_NUM_NoPerm_INS1FAILURE at INSERT: ORA-01031: insufficient privileges%1123.89-5.6e-70
TEST_PARMS                    BTT_NUM_USR_NULL_INS1FAILURE at INSERT: ORA-01400: cannot insert NULL into ("%"."AUD_BEG_USR")%1123.89-5.6e-70
TEST_SETS                     T1DBSABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1DBSFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1DBSGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1DBSHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1DBSABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1DBSFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1DBSGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1DBSHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1DBSABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBSHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1DBUABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1DBUHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1MTSFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1MTSGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1MTSHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     T1MTSABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1MTSFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1MTSGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1MTSHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     T1MTSABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTSHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_INS
TEST_SETS                     T1MTUABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     T1MTUHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
