
--
--  Install install_db Security Scripts for UTP
--
--  The 6 scripts included are:
--    -) create_glob_sec
--    -) create_ods_sec
--    -) create_integ_sec
--    -) create_oltp_sec
--    -) create_aa_sec
--    -) create_mods_sec
--


select ' -) create_glob_sec  ' as FILE_NAME from dual;


-- Script File "create_glob_sec"
--    Security script to Create Globals using generated code

   -- Application: Unit Test Parameters
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   03, 2012  08:38:44 PM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- 
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- 
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 




grant execute on glob to UTP_app
/
---- audit rename on glob by access
---- /

grant execute on pair_type to UTP_dml
/
---- audit rename on pair_type by access
---- /

grant execute on col_type to UTP_dml
/
---- audit rename on col_type by access
---- /

grant insert on util_log to UTP_app
/
-- grant update on util_log to UTP_app
-- /
grant delete on util_log to UTP_app
/
grant select on util_log to UTP_app
/
-- audit rename on util_log by access
-- /

grant execute on util to UTP_app
/
---- audit rename on util by access
---- /



select ' -) create_ods_sec  ' as FILE_NAME from dual;


-- Script File "create_ods_sec"
--    Security script to Create Online Data Store using generated code

   -- Application: Unit Test Parameters
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   03, 2012  08:38:44 PM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- 
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- 
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 




grant execute on global_parms_tab to UTP_dml
/
---- audit rename on global_parms_tab by access;
---- /

grant alter on global_parms_seq to UTP_dml
/
grant select on global_parms_seq to UTP_app
/
-- audit rename on global_parms_seq by access
-- /

grant select on global_parms to UTP_app
/
grant insert on global_parms to UTP_dml
/
grant update on global_parms to UTP_dml
/
grant delete on global_parms to UTP_dml
/
-- audit rename on global_parms by access
-- /

grant execute on parm_sets_tab to UTP_dml
/
---- audit rename on parm_sets_tab by access;
---- /

grant alter on parm_sets_seq to UTP_dml
/
grant select on parm_sets_seq to UTP_app
/
-- audit rename on parm_sets_seq by access
-- /

grant select on parm_sets to UTP_app
/
grant insert on parm_sets to UTP_dml
/
grant update on parm_sets to UTP_dml
/
grant delete on parm_sets to UTP_dml
/
-- audit rename on parm_sets by access
-- /

grant execute on test_parms_tab to UTP_dml
/
---- audit rename on test_parms_tab by access;
---- /

grant alter on test_parms_seq to UTP_dml
/
grant select on test_parms_seq to UTP_app
/
-- audit rename on test_parms_seq by access
-- /

grant select on test_parms to UTP_app
/
grant insert on test_parms to UTP_dml
/
grant update on test_parms to UTP_dml
/
grant delete on test_parms to UTP_dml
/
-- audit rename on test_parms by access
-- /

grant execute on test_sets_tab to UTP_dml
/
---- audit rename on test_sets_tab by access;
---- /

grant alter on test_sets_seq to UTP_dml
/
grant select on test_sets_seq to UTP_app
/
-- audit rename on test_sets_seq by access
-- /

grant select on test_sets to UTP_app
/
grant insert on test_sets to UTP_dml
/
grant update on test_sets to UTP_dml
/
grant delete on test_sets to UTP_dml
/
-- audit rename on test_sets by access
-- /



select ' -) create_integ_sec  ' as FILE_NAME from dual;


-- Script File "create_integ_sec"
--    Security script to Create ODS integrity using generated code

   -- Application: Unit Test Parameters
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   03, 2012  08:38:44 PM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- 
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- 
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 






select ' -) create_oltp_sec  ' as FILE_NAME from dual;


-- Script File "create_oltp_sec"
--    Security script to Create Online Transaction Processing using generated code

   -- Application: Unit Test Parameters
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   03, 2012  08:38:49 PM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- 
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- 
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 




grant execute on global_parms_view to UTP_dml
/
---- audit rename on global_parms_view by access
---- /

grant select on global_parms_act to UTP_app
/
grant insert on global_parms_act to UTP_app
/
grant update on global_parms_act to UTP_app
/
grant delete on global_parms_act to UTP_app
/
-- audit rename on global_parms_act by access
-- /

grant execute on global_parms_dml to UTP_app
/
---- audit rename on global_parms_dml by access
---- /

grant execute on parm_sets_view to UTP_dml
/
---- audit rename on parm_sets_view by access
---- /

grant select on parm_sets_act to UTP_app
/
grant insert on parm_sets_act to UTP_app
/
grant update on parm_sets_act to UTP_app
/
grant delete on parm_sets_act to UTP_app
/
-- audit rename on parm_sets_act by access
-- /

grant execute on parm_sets_dml to UTP_app
/
---- audit rename on parm_sets_dml by access
---- /

grant execute on test_parms_view to UTP_dml
/
---- audit rename on test_parms_view by access
---- /

grant select on test_parms_act to UTP_app
/
grant insert on test_parms_act to UTP_app
/
grant update on test_parms_act to UTP_app
/
grant delete on test_parms_act to UTP_app
/
-- audit rename on test_parms_act by access
-- /

grant execute on test_parms_dml to UTP_app
/
---- audit rename on test_parms_dml by access
---- /

grant execute on test_sets_view to UTP_dml
/
---- audit rename on test_sets_view by access
---- /

grant select on test_sets_act to UTP_app
/
grant insert on test_sets_act to UTP_app
/
grant update on test_sets_act to UTP_app
/
grant delete on test_sets_act to UTP_app
/
-- audit rename on test_sets_act by access
-- /

grant execute on test_sets_dml to UTP_app
/
---- audit rename on test_sets_dml by access
---- /



select ' -) create_aa_sec  ' as FILE_NAME from dual;



select ' -) create_mods_sec  ' as FILE_NAME from dual;


-- Script File "create_mods_sec"
--    Security script to Create Program Modules

   -- Application: Unit Test Parameters
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   03, 2012  08:38:49 PM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- 
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- 
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 





