
-- Script File "delete_ods"
--    Delete data from Online Data Store
--    
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    March     22, 2012  11:33:19 PM


----------------------------------------
select '***  exceptions  ***' as TABLE_NAME from dual;
----------------------------------------
delete from exceptions;

----------------------------------------
select '***  programs  ***' as TABLE_NAME from dual;
----------------------------------------
delete from programs;

----------------------------------------
select '***  check_cons  ***' as TABLE_NAME from dual;
----------------------------------------
delete from check_cons;

----------------------------------------
select '***  indexes  ***' as TABLE_NAME from dual;
----------------------------------------
delete from indexes;

----------------------------------------
select '***  tab_cols  ***' as TABLE_NAME from dual;
----------------------------------------
delete from tab_cols;

----------------------------------------
select '***  tables  ***' as TABLE_NAME from dual;
----------------------------------------
delete from tables;

----------------------------------------
select '***  domain_values  ***' as TABLE_NAME from dual;
----------------------------------------
delete from domain_values;

----------------------------------------
select '***  domains  ***' as TABLE_NAME from dual;
----------------------------------------
delete from domains;

----------------------------------------
select '***  file_lines  ***' as TABLE_NAME from dual;
----------------------------------------
delete from file_lines;

----------------------------------------
select '***  files  ***' as TABLE_NAME from dual;
----------------------------------------
delete from files;

----------------------------------------
select '***  applications  ***' as TABLE_NAME from dual;
----------------------------------------
delete from applications;
