
--
--  Install Mid-Tier Security Scripts for DTGEN
--
--  The 4 scripts included are:
--    -) create_gdst_sec
--    -) create_dist_sec
--    -) create_oltp_sec
--    -) create_mods_sec
--


select ' -) create_gdst_sec  ' as FILE_NAME from dual;


-- Script File "create_gdst_sec"
--    Security script to Create Distributed Globals using generated code
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  04:59:31 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--



grant execute on glob to DTGEN_app;
---- audit rename on glob by access;

grant execute on pair_type to DTGEN_dml;
---- audit rename on pair_type by access;

grant execute on col_type to DTGEN_dml;
---- audit rename on col_type by access;

grant insert on util_log to DTGEN_app;
-- grant update on util_log to DTGEN_app;
grant delete on util_log to DTGEN_app;
grant select on util_log to DTGEN_app;
-- audit rename on util_log by access;

grant execute on util to DTGEN_app;
---- audit rename on util by access;



select ' -) create_dist_sec  ' as FILE_NAME from dual;


-- Script File "create_dist_sec"
--    Security script to Create distributed integrity using generated code
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  04:59:57 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--



grant execute on applications_tab to DTGEN_dml;
---- audit rename on applications_tab by access;

-- audit rename on applications_seq by access;

grant select on applications to DTGEN_app;
-- audit rename on applications by access;

grant execute on files_tab to DTGEN_dml;
---- audit rename on files_tab by access;

-- audit rename on files_seq by access;

grant select on files to DTGEN_app;
-- audit rename on files by access;

grant execute on file_lines_tab to DTGEN_dml;
---- audit rename on file_lines_tab by access;

-- audit rename on file_lines_seq by access;

grant select on file_lines to DTGEN_app;
-- audit rename on file_lines by access;

grant execute on domains_tab to DTGEN_dml;
---- audit rename on domains_tab by access;

-- audit rename on domains_seq by access;

grant select on domains to DTGEN_app;
-- audit rename on domains by access;

grant execute on domain_values_tab to DTGEN_dml;
---- audit rename on domain_values_tab by access;

-- audit rename on domain_values_seq by access;

grant select on domain_values to DTGEN_app;
-- audit rename on domain_values by access;

grant execute on tables_tab to DTGEN_dml;
---- audit rename on tables_tab by access;

-- audit rename on tables_seq by access;

grant select on tables to DTGEN_app;
-- audit rename on tables by access;

grant execute on tab_cols_tab to DTGEN_dml;
---- audit rename on tab_cols_tab by access;

-- audit rename on tab_cols_seq by access;

grant select on tab_cols to DTGEN_app;
-- audit rename on tab_cols by access;

grant execute on tab_inds_tab to DTGEN_dml;
---- audit rename on tab_inds_tab by access;

-- audit rename on tab_inds_seq by access;

grant select on tab_inds to DTGEN_app;
-- audit rename on tab_inds by access;

grant execute on check_cons_tab to DTGEN_dml;
---- audit rename on check_cons_tab by access;

-- audit rename on check_cons_seq by access;

grant select on check_cons to DTGEN_app;
-- audit rename on check_cons by access;

grant execute on programs_tab to DTGEN_dml;
---- audit rename on programs_tab by access;

-- audit rename on programs_seq by access;

grant select on programs to DTGEN_app;
-- audit rename on programs by access;

grant execute on exceptions_tab to DTGEN_dml;
---- audit rename on exceptions_tab by access;

-- audit rename on exceptions_seq by access;

grant select on exceptions to DTGEN_app;
-- audit rename on exceptions by access;



select ' -) create_oltp_sec  ' as FILE_NAME from dual;


-- Script File "create_oltp_sec"
--    Security script to Create Online Transaction Processing using generated code
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  05:00:29 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--



grant execute on applications_view to DTGEN_dml;
---- audit rename on applications_view by access;

grant select on applications_act to DTGEN_app;
grant insert on applications_act to DTGEN_app;
grant update on applications_act to DTGEN_app;
grant delete on applications_act to DTGEN_app;
-- audit rename on applications_act by access;

grant execute on applications_dml to DTGEN_app;
---- audit rename on applications_dml by access;

grant execute on files_view to DTGEN_dml;
---- audit rename on files_view by access;

grant select on files_act to DTGEN_app;
grant insert on files_act to DTGEN_app;
grant update on files_act to DTGEN_app;
grant delete on files_act to DTGEN_app;
-- audit rename on files_act by access;

grant execute on files_dml to DTGEN_app;
---- audit rename on files_dml by access;

grant execute on file_lines_view to DTGEN_dml;
---- audit rename on file_lines_view by access;

grant select on file_lines_act to DTGEN_app;
grant insert on file_lines_act to DTGEN_app;
grant update on file_lines_act to DTGEN_app;
grant delete on file_lines_act to DTGEN_app;
-- audit rename on file_lines_act by access;

grant execute on file_lines_dml to DTGEN_app;
---- audit rename on file_lines_dml by access;

grant execute on domains_view to DTGEN_dml;
---- audit rename on domains_view by access;

grant select on domains_act to DTGEN_app;
grant insert on domains_act to DTGEN_app;
grant update on domains_act to DTGEN_app;
grant delete on domains_act to DTGEN_app;
-- audit rename on domains_act by access;

grant execute on domains_dml to DTGEN_app;
---- audit rename on domains_dml by access;

grant execute on domain_values_view to DTGEN_dml;
---- audit rename on domain_values_view by access;

grant select on domain_values_act to DTGEN_app;
grant insert on domain_values_act to DTGEN_app;
grant update on domain_values_act to DTGEN_app;
grant delete on domain_values_act to DTGEN_app;
-- audit rename on domain_values_act by access;

grant execute on domain_values_dml to DTGEN_app;
---- audit rename on domain_values_dml by access;

grant execute on tables_view to DTGEN_dml;
---- audit rename on tables_view by access;

grant select on tables_act to DTGEN_app;
grant insert on tables_act to DTGEN_app;
grant update on tables_act to DTGEN_app;
grant delete on tables_act to DTGEN_app;
-- audit rename on tables_act by access;

grant execute on tables_dml to DTGEN_app;
---- audit rename on tables_dml by access;

grant execute on tab_cols_view to DTGEN_dml;
---- audit rename on tab_cols_view by access;

grant select on tab_cols_act to DTGEN_app;
grant insert on tab_cols_act to DTGEN_app;
grant update on tab_cols_act to DTGEN_app;
grant delete on tab_cols_act to DTGEN_app;
-- audit rename on tab_cols_act by access;

grant execute on tab_cols_dml to DTGEN_app;
---- audit rename on tab_cols_dml by access;

grant execute on tab_inds_view to DTGEN_dml;
---- audit rename on tab_inds_view by access;

grant select on tab_inds_act to DTGEN_app;
grant insert on tab_inds_act to DTGEN_app;
grant update on tab_inds_act to DTGEN_app;
grant delete on tab_inds_act to DTGEN_app;
-- audit rename on tab_inds_act by access;

grant execute on tab_inds_dml to DTGEN_app;
---- audit rename on tab_inds_dml by access;

grant execute on check_cons_view to DTGEN_dml;
---- audit rename on check_cons_view by access;

grant select on check_cons_act to DTGEN_app;
grant insert on check_cons_act to DTGEN_app;
grant update on check_cons_act to DTGEN_app;
grant delete on check_cons_act to DTGEN_app;
-- audit rename on check_cons_act by access;

grant execute on check_cons_dml to DTGEN_app;
---- audit rename on check_cons_dml by access;

grant execute on programs_view to DTGEN_dml;
---- audit rename on programs_view by access;

grant select on programs_act to DTGEN_app;
grant insert on programs_act to DTGEN_app;
grant update on programs_act to DTGEN_app;
grant delete on programs_act to DTGEN_app;
-- audit rename on programs_act by access;

grant execute on programs_dml to DTGEN_app;
---- audit rename on programs_dml by access;

grant execute on exceptions_view to DTGEN_dml;
---- audit rename on exceptions_view by access;

grant select on exceptions_act to DTGEN_app;
grant insert on exceptions_act to DTGEN_app;
grant update on exceptions_act to DTGEN_app;
grant delete on exceptions_act to DTGEN_app;
-- audit rename on exceptions_act by access;

grant execute on exceptions_dml to DTGEN_app;
---- audit rename on exceptions_dml by access;



select ' -) create_mods_sec  ' as FILE_NAME from dual;


-- Script File "create_mods_sec"
--    Security script to Create Program Modules
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  05:00:30 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--



grant execute on dtgen_util to DTGEN_app;
---- audit rename on dtgen_util by access;

grant execute on generate to DTGEN_app;
---- audit rename on generate by access;

grant execute on gui_util to DTGEN_app;
---- audit rename on gui_util by access;


