
--
--  Install User Synonym Scripts for DTGEN
--
--  The 1 scripts included are:
--    -) create_usyn
--


select ' -) create_usyn  ' as FILE_NAME from dual;


-- Script File "create_usyn"
--    Create Synonyms for Users
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  05:00:30 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--


create synonym util
   for DTGEN.util;
create synonym util_log
   for DTGEN.util_log;
create synonym glob
   for DTGEN.glob;

create synonym dtgen_util
   for DTGEN.dtgen_util;
create synonym generate
   for DTGEN.generate;
create synonym gui_util
   for DTGEN.gui_util;

----------------------------------------
select '***  applications  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "applications_dml.get_next_id" instead of sequence
--create synonym applications_seq
--   for DTGEN.applications_seq;
create synonym applications
   for DTGEN.applications;
create synonym applications_dml
   for DTGEN.applications_dml;
create synonym applications_act
   for DTGEN.applications_act;

----------------------------------------
select '***  files  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "files_dml.get_next_id" instead of sequence
--create synonym files_seq
--   for DTGEN.files_seq;
create synonym files
   for DTGEN.files;
create synonym files_dml
   for DTGEN.files_dml;
create synonym files_act
   for DTGEN.files_act;

----------------------------------------
select '***  file_lines  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "file_lines_dml.get_next_id" instead of sequence
--create synonym file_lines_seq
--   for DTGEN.file_lines_seq;
create synonym file_lines
   for DTGEN.file_lines;
create synonym file_lines_dml
   for DTGEN.file_lines_dml;
create synonym file_lines_act
   for DTGEN.file_lines_act;

----------------------------------------
select '***  domains  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "domains_dml.get_next_id" instead of sequence
--create synonym domains_seq
--   for DTGEN.domains_seq;
create synonym domains
   for DTGEN.domains;
create synonym domains_dml
   for DTGEN.domains_dml;
create synonym domains_act
   for DTGEN.domains_act;

----------------------------------------
select '***  domain_values  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "domain_values_dml.get_next_id" instead of sequence
--create synonym domain_values_seq
--   for DTGEN.domain_values_seq;
create synonym domain_values
   for DTGEN.domain_values;
create synonym domain_values_dml
   for DTGEN.domain_values_dml;
create synonym domain_values_act
   for DTGEN.domain_values_act;

----------------------------------------
select '***  tables  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "tables_dml.get_next_id" instead of sequence
--create synonym tables_seq
--   for DTGEN.tables_seq;
create synonym tables
   for DTGEN.tables;
create synonym tables_dml
   for DTGEN.tables_dml;
create synonym tables_act
   for DTGEN.tables_act;

----------------------------------------
select '***  tab_cols  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "tab_cols_dml.get_next_id" instead of sequence
--create synonym tab_cols_seq
--   for DTGEN.tab_cols_seq;
create synonym tab_cols
   for DTGEN.tab_cols;
create synonym tab_cols_dml
   for DTGEN.tab_cols_dml;
create synonym tab_cols_act
   for DTGEN.tab_cols_act;

----------------------------------------
select '***  tab_inds  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "tab_inds_dml.get_next_id" instead of sequence
--create synonym tab_inds_seq
--   for DTGEN.tab_inds_seq;
create synonym tab_inds
   for DTGEN.tab_inds;
create synonym tab_inds_dml
   for DTGEN.tab_inds_dml;
create synonym tab_inds_act
   for DTGEN.tab_inds_act;

----------------------------------------
select '***  check_cons  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "check_cons_dml.get_next_id" instead of sequence
--create synonym check_cons_seq
--   for DTGEN.check_cons_seq;
create synonym check_cons
   for DTGEN.check_cons;
create synonym check_cons_dml
   for DTGEN.check_cons_dml;
create synonym check_cons_act
   for DTGEN.check_cons_act;

----------------------------------------
select '***  programs  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "programs_dml.get_next_id" instead of sequence
--create synonym programs_seq
--   for DTGEN.programs_seq;
create synonym programs
   for DTGEN.programs;
create synonym programs_dml
   for DTGEN.programs_dml;
create synonym programs_act
   for DTGEN.programs_act;

----------------------------------------
select '***  exceptions  ***' as TABLE_NAME from dual;
----------------------------------------

--  Must use "exceptions_dml.get_next_id" instead of sequence
--create synonym exceptions_seq
--   for DTGEN.exceptions_seq;
create synonym exceptions
   for DTGEN.exceptions;
create synonym exceptions_dml
   for DTGEN.exceptions_dml;
create synonym exceptions_act
   for DTGEN.exceptions_act;


