
--
--  Uninstall Mid-Tier Scripts for DTGEN
--
--  The 4 scripts included are:
--    -) drop_mods
--    -) drop_oltp
--    -) drop_dist
--    -) drop_gdst
--


select ' -) drop_mods  ' as FILE_NAME from dual;


-- Script File "drop_mods"
--    Drop Program Modules
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  04:59:25 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--


drop PACKAGE gui_util;
drop PACKAGE generate;
drop PACKAGE dtgen_util;


select ' -) drop_oltp  ' as FILE_NAME from dual;


-- Script File "drop_oltp"
--    Drop Online Data Store using generated code
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  04:59:25 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--


----------------------------------------
select '***  exceptions  ***' as TABLE_NAME from dual;
----------------------------------------
drop view exceptions_act;
drop package exceptions_view;
drop package exceptions_dml;

----------------------------------------
select '***  programs  ***' as TABLE_NAME from dual;
----------------------------------------
drop view programs_act;
drop package programs_view;
drop package programs_dml;

----------------------------------------
select '***  check_cons  ***' as TABLE_NAME from dual;
----------------------------------------
drop view check_cons_act;
drop package check_cons_view;
drop package check_cons_dml;

----------------------------------------
select '***  tab_inds  ***' as TABLE_NAME from dual;
----------------------------------------
drop view tab_inds_act;
drop package tab_inds_view;
drop package tab_inds_dml;

----------------------------------------
select '***  tab_cols  ***' as TABLE_NAME from dual;
----------------------------------------
drop view tab_cols_act;
drop package tab_cols_view;
drop package tab_cols_dml;

----------------------------------------
select '***  tables  ***' as TABLE_NAME from dual;
----------------------------------------
drop view tables_act;
drop package tables_view;
drop package tables_dml;

----------------------------------------
select '***  domain_values  ***' as TABLE_NAME from dual;
----------------------------------------
drop view domain_values_act;
drop package domain_values_view;
drop package domain_values_dml;

----------------------------------------
select '***  domains  ***' as TABLE_NAME from dual;
----------------------------------------
drop view domains_act;
drop package domains_view;
drop package domains_dml;

----------------------------------------
select '***  file_lines  ***' as TABLE_NAME from dual;
----------------------------------------
drop view file_lines_act;
drop package file_lines_view;
drop package file_lines_dml;

----------------------------------------
select '***  files  ***' as TABLE_NAME from dual;
----------------------------------------
drop view files_act;
drop package files_view;
drop package files_dml;

----------------------------------------
select '***  applications  ***' as TABLE_NAME from dual;
----------------------------------------
drop view applications_act;
drop package applications_view;
drop package applications_dml;

select view_name, text_length, view_type_owner
 from  user_views;
select substr(object_name,1,30), object_type, status
 from  user_objects
 where object_type = 'PACKAGE BODY'
  and  object_name not like '%_POP';


select ' -) drop_dist  ' as FILE_NAME from dual;


-- Script File "drop_dist"
--    Drop distributed integrity using generated code
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  04:59:26 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--


----------------------------------------
select '***  exceptions  ***' as TABLE_NAME from dual;
----------------------------------------
drop package exceptions_tab;
drop view exceptions;
drop synonym exceptions_seq;

----------------------------------------
select '***  programs  ***' as TABLE_NAME from dual;
----------------------------------------
drop package programs_tab;
drop view programs;
drop synonym programs_seq;

----------------------------------------
select '***  check_cons  ***' as TABLE_NAME from dual;
----------------------------------------
drop package check_cons_tab;
drop view check_cons;
drop synonym check_cons_seq;

----------------------------------------
select '***  tab_inds  ***' as TABLE_NAME from dual;
----------------------------------------
drop package tab_inds_tab;
drop view tab_inds;
drop synonym tab_inds_seq;

----------------------------------------
select '***  tab_cols  ***' as TABLE_NAME from dual;
----------------------------------------
drop package tab_cols_tab;
drop view tab_cols;
drop synonym tab_cols_seq;

----------------------------------------
select '***  tables  ***' as TABLE_NAME from dual;
----------------------------------------
drop package tables_tab;
drop view tables;
drop synonym tables_seq;

----------------------------------------
select '***  domain_values  ***' as TABLE_NAME from dual;
----------------------------------------
drop package domain_values_tab;
drop view domain_values;
drop synonym domain_values_seq;

----------------------------------------
select '***  domains  ***' as TABLE_NAME from dual;
----------------------------------------
drop package domains_tab;
drop view domains;
drop synonym domains_seq;

----------------------------------------
select '***  file_lines  ***' as TABLE_NAME from dual;
----------------------------------------
drop package file_lines_tab;
drop view file_lines;
drop synonym file_lines_seq;

----------------------------------------
select '***  files  ***' as TABLE_NAME from dual;
----------------------------------------
drop package files_tab;
drop view files;
drop synonym files_seq;

----------------------------------------
select '***  applications  ***' as TABLE_NAME from dual;
----------------------------------------
drop package applications_tab;
drop view applications;
drop synonym applications_seq;

select trigger_name, trigger_type, table_name
 from  user_triggers where base_object_type = 'TABLE';
select substr(owner||'.'||constraint_name,1,40)
      ,constraint_type, table_name
 from  user_constraints
 where constraint_type not in ('P','U','R');


select ' -) drop_gdst  ' as FILE_NAME from dual;


-- Script File "drop_gdst"
--    Drop Distributed Globals using generated code
--
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    August    09, 2012  04:59:27 PM

--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--


drop package util;
drop table util_log;
drop type col_type;
drop type pair_type;
drop package glob;
drop database link DTGEN_db;

select substr(object_name,1,30), object_type, status
 from  user_objects;

