--
-- DTGen SQL*Loader Control File
--    Full data dump of the UTP application
--    
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    October   02, 2012  08:12:57 PM
--
-- sqlldr username/password CONTROL=FILENAME
--
load data infile *
into table APPLICATIONS_ACT APPEND when key = 'APPLICATIONS                  ' fields terminated by ''
   (key FILLER position(1:31), abbr CHAR(5), name CHAR(30), db_schema CHAR(30), db_schema_exp CHAR(1), apex_schema CHAR(30), apex_ws_name CHAR(30), apex_app_name CHAR(30), dbid CHAR(2000), db_auth CHAR(200), description CHAR(1000), ts_null_override CHAR(1), ts_onln_data CHAR(30), ts_onln_indx CHAR(30), ts_hist_data CHAR(30), ts_hist_indx CHAR(30), usr_datatype CHAR(20), usr_frgn_key CHAR(100), copyright CHAR(4000))
into table DOMAINS_ACT APPEND when key = 'DOMAINS                       ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), abbr CHAR(5), name CHAR(20), fold CHAR(1), len FLOAT EXTERNAL, description CHAR(1000))
into table EXCEPTIONS_ACT APPEND when key = 'EXCEPTIONS                    ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), code FLOAT EXTERNAL, name CHAR(30), message CHAR(2048), cause CHAR(2048), action CHAR(2048))
into table PROGRAMS_ACT APPEND when key = 'PROGRAMS                      ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), name CHAR(30), type CHAR(30), description CHAR(1000))
into table TABLES_ACT APPEND when key = 'TABLES                        ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), abbr CHAR(5), name CHAR(15), seq FLOAT EXTERNAL, type CHAR(3), group_name CHAR(30), mv_refresh_hr FLOAT EXTERNAL, ts_onln_data CHAR(30), ts_onln_indx CHAR(30), ts_hist_data CHAR(30), ts_hist_indx CHAR(30), description CHAR(1000))
into table CHECK_CONS_ACT APPEND when key = 'CHECK_CONS                    ' fields terminated by ''
   (key FILLER position(1:31), tables_nk1 CHAR(5), tables_nk2 CHAR(5), seq FLOAT EXTERNAL, text CHAR(1000), description CHAR(1000))
into table DOMAIN_VALUES_ACT APPEND when key = 'DOMAIN_VALUES                 ' fields terminated by ''
   (key FILLER position(1:31), domains_nk1 CHAR(5), domains_nk2 CHAR(5), value CHAR(100), seq FLOAT EXTERNAL, description CHAR(1000))
into table TAB_COLS_ACT APPEND when key = 'TAB_COLS                      ' fields terminated by ''
   (key FILLER position(1:31), tables_nk1 CHAR(5), tables_nk2 CHAR(5), name CHAR(25), seq FLOAT EXTERNAL, nk FLOAT EXTERNAL, req CHAR(1), fk_prefix CHAR(4), fk_tables_nk1 CHAR(5), fk_tables_nk2 CHAR(5), d_domains_nk1 CHAR(5), d_domains_nk2 CHAR(5), type CHAR(30), len FLOAT EXTERNAL, scale FLOAT EXTERNAL, fold CHAR(1), default_value CHAR(1000), upd_res_pct FLOAT EXTERNAL, description CHAR(1000))
into table TAB_INDS_ACT APPEND when key = 'TAB_INDS                      ' fields terminated by ''
   (key FILLER position(1:31), tab_cols_nk1 CHAR(5), tab_cols_nk2 CHAR(5), tab_cols_nk3 CHAR(25), tag CHAR(4), seq FLOAT EXTERNAL)
BEGINDATA
APPLICATIONS                  UTPUnit Test ParametersDTGen Unit Testing Parameter DatabaseCopyright (c) 2012, Duane.Dieterich@gmail.com
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
DOMAINS                       UTPTFT_Or_FU1True or False Flags for Values
TABLES                        UTPGPglobal_parms1NONGlobal Parameters that affect generated systems "across the board".
TABLES                        UTPPSparm_sets2NONParameter Sets are groups of test results and parameters used be each unit test.
TABLES                        UTPTPtest_parms3NONActual test parameter values, sequenced for each parameter set.
TABLES                        UTPTStest_sets4NONIndividual tests and their associated parameter sets.
DOMAIN_VALUES                 UTPTFT1True
DOMAIN_VALUES                 UTPTFF2False
TAB_COLS                      UTPGPglobal_set11VARCHAR21Global Set Name/Code
TAB_COLS                      UTPGPdb_constraints2XUTPTFDatabase Constraints setting for  the DTGen GLOB Package.
TAB_COLS                      UTPGPfold_strings3XUTPTFFold Strings setting for  the DTGen GLOB Package.
TAB_COLS                      UTPGPignore_no_change4XUTPTFIgnore No Change setting for  the DTGen GLOB Package.
TAB_COLS                      UTPGPdescription5VARCHAR22000Description of this Global Set
TAB_COLS                      UTPPSparm_set11VARCHAR230Parameter Set Name
TAB_COLS                      UTPPSdescription2VARCHAR22000Description for this Parameter Set
TAB_COLS                      UTPTPparm_set11UTPPSParameter Set Name
TAB_COLS                      UTPTPparm_seq22NUMBERParameter Set Sequence Number
TAB_COLS                      UTPTPresult_txt3VARCHAR24000Expected Result String 
TAB_COLS                      UTPTPval010VARCHAR24000Value 0 of the Parameter Set
TAB_COLS                      UTPTPval111VARCHAR24000Value 1 of the Parameter Set
TAB_COLS                      UTPTPval212VARCHAR24000Value 2 of the Parameter Set
TAB_COLS                      UTPTPval313VARCHAR24000Value 3 of the Parameter Set
TAB_COLS                      UTPTPval414VARCHAR24000Value 4 of the Parameter Set
TAB_COLS                      UTPTPval515VARCHAR24000Value 5 of the Parameter Set
TAB_COLS                      UTPTPval616VARCHAR24000Value 6 of the Parameter Set
TAB_COLS                      UTPTPval717VARCHAR24000Value 7 of the Parameter Set
TAB_COLS                      UTPTPval818VARCHAR24000Value 8 of the Parameter Set
TAB_COLS                      UTPTPval919VARCHAR24000Value 9 of the Parameter Set
TAB_COLS                      UTPTPdescription20VARCHAR22000Description for this Parameter Set Sequence
TAB_COLS                      UTPTSuser_name11VARCHAR230User name running this unit test.
TAB_COLS                      UTPTSglobal_set22UTPGPGlobal set used for this unit test.
TAB_COLS                      UTPTStest_name33VARCHAR260Test name used for this unit test.
TAB_COLS                      UTPTSparm_set44UTPPSSequence of Parameter Values and Result for this unit test.
TAB_COLS                      UTPTSdescription5VARCHAR22000Description of this unit test.
TAB_INDS                      UTPGPdb_constraintsux11
TAB_INDS                      UTPGPfold_stringsux12
TAB_INDS                      UTPGPignore_no_changeux13
