--
-- DTGen SQL*Loader Control File
--    Full data dump of the TST1 application
--    
--    Generated by DTGen (http://code.google.com/p/dtgen)
--    September 06, 2012  02:39:32 PM
--
-- sqlldr username/password CONTROL=FILENAME
--
load data infile *
into table APPLICATIONS_ACT APPEND when key = 'APPLICATIONS                  ' fields terminated by ''
   (key FILLER position(1:31), abbr CHAR(5), name CHAR(30), db_schema CHAR(30), db_schema_exp CHAR(1), apex_schema CHAR(30), apex_ws_name CHAR(30), apex_app_name CHAR(30), dbid CHAR(2000), db_auth CHAR(200), description CHAR(1000), ts_null_override CHAR(1), ts_onln_data CHAR(30), ts_onln_indx CHAR(30), ts_hist_data CHAR(30), ts_hist_indx CHAR(30), usr_datatype CHAR(20), usr_frgn_key CHAR(100), copyright CHAR(4000))
into table DOMAINS_ACT APPEND when key = 'DOMAINS                       ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), abbr CHAR(5), name CHAR(20), fold CHAR(1), len FLOAT EXTERNAL, description CHAR(1000))
into table EXCEPTIONS_ACT APPEND when key = 'EXCEPTIONS                    ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), code FLOAT EXTERNAL, name CHAR(30), message CHAR(2048), cause CHAR(2048), action CHAR(2048))
into table PROGRAMS_ACT APPEND when key = 'PROGRAMS                      ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), name CHAR(30), type CHAR(30), description CHAR(1000))
into table TABLES_ACT APPEND when key = 'TABLES                        ' fields terminated by ''
   (key FILLER position(1:31), applications_nk1 CHAR(5), abbr CHAR(5), name CHAR(15), seq FLOAT EXTERNAL, type CHAR(3), group_name CHAR(30), mv_refresh_hr FLOAT EXTERNAL, ts_onln_data CHAR(30), ts_onln_indx CHAR(30), ts_hist_data CHAR(30), ts_hist_indx CHAR(30), description CHAR(1000))
into table CHECK_CONS_ACT APPEND when key = 'CHECK_CONS                    ' fields terminated by ''
   (key FILLER position(1:31), tables_nk1 CHAR(5), tables_nk2 CHAR(5), seq FLOAT EXTERNAL, text CHAR(1000), description CHAR(1000))
into table DOMAIN_VALUES_ACT APPEND when key = 'DOMAIN_VALUES                 ' fields terminated by ''
   (key FILLER position(1:31), domains_nk1 CHAR(5), domains_nk2 CHAR(5), value CHAR(100), seq FLOAT EXTERNAL, description CHAR(1000))
into table TAB_COLS_ACT APPEND when key = 'TAB_COLS                      ' fields terminated by ''
   (key FILLER position(1:31), tables_nk1 CHAR(5), tables_nk2 CHAR(5), name CHAR(25), seq FLOAT EXTERNAL, nk FLOAT EXTERNAL, req CHAR(1), fk_prefix CHAR(4), fk_tables_nk1 CHAR(5), fk_tables_nk2 CHAR(5), d_domains_nk1 CHAR(5), d_domains_nk2 CHAR(5), type CHAR(30), len FLOAT EXTERNAL, scale FLOAT EXTERNAL, fold CHAR(1), default_value CHAR(1000), upd_res_pct FLOAT EXTERNAL, description CHAR(1000))
into table TAB_INDS_ACT APPEND when key = 'TAB_INDS                      ' fields terminated by ''
   (key FILLER position(1:31), tab_cols_nk1 CHAR(5), tab_cols_nk2 CHAR(5), tab_cols_nk3 CHAR(25), tag CHAR(4), seq FLOAT EXTERNAL)
BEGINDATA
APPLICATIONS                  TST1Test Application 1Test Application 1Xtest_onln_data_defaulttest_onln_indx_defaulttest_hist_data_defaulttest_hist_indx_default*** This is only a test ***
PROGRAMS                      TST1test_rigPACKAGEProvides Unit Testing functions and procedures
TABLES                        TST1T1ANt1a_non10NONDTCtest_onln_data_specialtest_onln_indx_specialtest_hist_data_specialtest_hist_indx_specialDatatype Support for Columns Test Table, NON Table Type
TABLES                        TST1T1ALt1a_log11LOGDTCtest_onln_data_specialtest_onln_indx_specialtest_hist_data_specialtest_hist_indx_specialDatatype Support for Columns Test Table, LOG Table Type
TABLES                        TST1T1AEt1a_eff12EFFDTCtest_onln_data_specialtest_onln_indx_specialtest_hist_data_specialtest_hist_indx_specialDatatype Support for Columns Test Table, EFF Table Type
TAB_COLS                      TST1T1AEseq11NUMBERSequenced Natural Key
TAB_COLS                      TST1T1AEnum_plain11NUMBERDTC Number test, plain
TAB_COLS                      TST1T1AEnum_min_len12NUMBER1DTC Number with minimum length
TAB_COLS                      TST1T1AEnum_min_min13NUMBER1-84DTC Number with minimum length and minimum scale
TAB_COLS                      TST1T1AEnum_min_max14NUMBER1127DTC Number with minimum length and maximum scale
TAB_COLS                      TST1T1AEnum_max_len15NUMBER38DTC Number with maximum length
TAB_COLS                      TST1T1AEnum_max_min16NUMBER38-84DTC Number with maximum length and minimum scale
TAB_COLS                      TST1T1AEnum_max_max17NUMBER38127DTC Number with maximum length and maximum scale
TAB_COLS                      TST1T1ALseq11NUMBERSequenced Natural Key
TAB_COLS                      TST1T1ALnum_plain11NUMBERDTC Number test, plain
TAB_COLS                      TST1T1ALnum_min_len12NUMBER1DTC Number with minimum length
TAB_COLS                      TST1T1ALnum_min_min13NUMBER1-84DTC Number with minimum length and minimum scale
TAB_COLS                      TST1T1ALnum_min_max14NUMBER1127DTC Number with minimum length and maximum scale
TAB_COLS                      TST1T1ALnum_max_len15NUMBER38DTC Number with maximum length
TAB_COLS                      TST1T1ALnum_max_min16NUMBER38-84DTC Number with maximum length and minimum scale
TAB_COLS                      TST1T1ALnum_max_max17NUMBER38127DTC Number with maximum length and maximum scale
TAB_COLS                      TST1T1ANseq11NUMBERSequenced Natural Key
TAB_COLS                      TST1T1ANnum_plain11NUMBERDTC Number test, plain
TAB_COLS                      TST1T1ANnum_min_len12NUMBER1DTC Number with minimum length
TAB_COLS                      TST1T1ANnum_min_min13NUMBER1-84DTC Number with minimum length and minimum scale
TAB_COLS                      TST1T1ANnum_min_max14NUMBER1127DTC Number with minimum length and maximum scale
TAB_COLS                      TST1T1ANnum_max_len15NUMBER38DTC Number with maximum length
TAB_COLS                      TST1T1ANnum_max_min16NUMBER38-84DTC Number with maximum length and minimum scale
TAB_COLS                      TST1T1ANnum_max_max17NUMBER38127DTC Number with maximum length and maximum scale

