--
-- Unit Test SQL*Loader Control File
--
-- sqlldr username/password CONTROL=FILENAME
--
load data infile *
into table GLOBAL_PARMS append
   when key = 'GLOBAL_PARMS                  '
   fields terminated by ''
   trailing nullcols
      (key FILLER position(1:31)
      ,global_set        CHAR(1)
      ,db_constraints    CHAR(1)
      ,fold_strings      CHAR(1)
      ,ignore_no_change  CHAR(1)
      ,description       CHAR(2000) )
into table PARM_SETS append
   when key = 'PARM_SETS                     '
   fields terminated by ''
   trailing nullcols
      (key FILLER   position(1:31)
      ,parm_set     CHAR(30)
      ,description  CHAR(2000) )
into table TEST_PARMS append
   when key = 'TEST_PARMS                    '
   fields terminated by ''
   trailing nullcols
      (key FILLER   position(1:31)
      ,parm_set     CHAR(30)
      ,parm_seq     FLOAT EXTERNAL
      ,result_txt   CHAR(4000)
      ,val0         CHAR(4000)
      ,val1         CHAR(4000)
      ,val2         CHAR(4000)
      ,val3         CHAR(4000)
      ,val4         CHAR(4000)
      ,val5         CHAR(4000)
      ,val6         CHAR(4000)
      ,val7         CHAR(4000)
      ,val8         CHAR(4000)
      ,val9         CHAR(4000)
      ,description  CHAR(2000) )
into table TEST_SETS append
   when key = 'TEST_SETS                     '
   fields terminated by ''
   trailing nullcols
      (key FILLER position(1:31)
      ,user_name    CHAR(30)
      ,global_set   CHAR(1)
      ,test_name    CHAR(30)
      ,parm_set     CHAR(30)
      ,description  CHAR(2000) )
BEGINDATA
GLOBAL_PARMS                  ATTT
GLOBAL_PARMS                  BTTF
GLOBAL_PARMS                  CTFT
GLOBAL_PARMS                  DTFF
GLOBAL_PARMS                  EFTT
GLOBAL_PARMS                  FFTF
GLOBAL_PARMS                  GFFT
GLOBAL_PARMS                  HFFF
PARM_SETS                     BTT_NUM_PASSHappy Path Basic Table Test (DTC, POPT, Partial HAT, Partial APIT, and Partial DMLIT) for Plain Numbers
PARM_SETS                     BTT_NUM_LOG_NoIntDBFail Path Basic Table Test for SQL LOG Table Insert with no Integrity (Triggers) at Database Server
PARM_SETS                     BTT_NUM_EFF_NoIntDBFail Path Basic Table Test for SQL EFF Table Insert with no Integrity (Triggers) at Database Server
PARM_SETS                     BTT_NUM_NoPerm_MTFail Path Basic Table Test for SQL LOG/EFF Tables Insert with unknown missing permission at Mid-Tier Serverber
PARM_SETS                     BTT_NUM_USR_NULL_MTFail Path Basic Table Test for SQL LOG/EFF ACT Views Insert DB_CONSTRAINTS = TRUE and no Integrity (Triggers)
TEST_PARMS                    BTT_NUM_PASS1SUCCESS11456.78
TEST_PARMS                    BTT_NUM_PASS2SUCCESS12123.89-5.6e-70
TEST_PARMS                    BTT_NUM_PASS3SUCCESS13-1.2e-403.4e50
TEST_PARMS                    BTT_NUM_PASS4SUCCESS141.2e50
TEST_PARMS                    BTT_NUM_LOG_NoIntDB1FAILURE at UPDATE: ORA-20000: t1a_log_aud row_cnt is not 1:%1123.89-5.6e-70
TEST_PARMS                    BTT_NUM_EFF_NoIntDB1FAILURE at UPDATE: ORA-20000: t1a_eff_hist row_cnt is not 1:%1123.89-5.6e-70
TEST_PARMS                    BTT_NUM_NoPerm_MT1FAILURE at INSERT: ORA-01031: insufficient privileges%1123.89-5.6e-70
TEST_PARMS                    BTT_NUM_USR_NULL_MT1FAILURE at INSERT: ORA-01400: cannot insert NULL into ("%1123.89-5.6e-70
TEST_SETS                     TDBSTABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSTFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSTGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSTHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSTABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSTFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSTGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSTHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSTABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSTHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUTFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUTGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUTHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUTABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUTFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUTGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUTHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUTABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUTHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSTDODABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSTDODHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUTDODABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUTDODHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSNFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSNGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSNHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBSNABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSNFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSNGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSNHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBSNABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBSNHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUNFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUNGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUNHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_LOG_NoIntDB
TEST_SETS                     TDBUNABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNABTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUNFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUNGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUNHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_EFF_NoIntDB
TEST_SETS                     TDBUNABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNABTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TDBUNHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNABTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNABTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNABTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNABTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODABTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTSNDODABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODABTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTSNDODEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTSNDODHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODABTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODBBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODCBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODDBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODEBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODFBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODGBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODHBTT_SQLTAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODABTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODBBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODCBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODDBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODEBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODFBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODGBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODHBTT_SQLACT_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODABTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODBBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODCBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODDBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODEBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODFBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODGBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODHBTT_APITAB_NON_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODABTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODBBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODCBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODDBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODEBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODFBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODGBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODHBTT_SQLTAB_LOG_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODABTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODBBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODCBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODDBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODEBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODFBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODGBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODHBTT_SQLACT_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODABTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODBBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODCBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODDBTT_APITAB_LOG_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODEBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODFBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODGBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODHBTT_APITAB_LOG_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODABTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODBBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODCBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODDBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODEBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODFBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODGBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODHBTT_SQLTAB_EFF_NUM_PLAINBTT_NUM_NoPerm_MT
TEST_SETS                     TMTUNDODABTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODBBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODCBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODDBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODEBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODFBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODGBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODHBTT_SQLACT_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODABTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODBBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODCBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODDBTT_APITAB_EFF_NUM_PLAINBTT_NUM_USR_NULL_MT
TEST_SETS                     TMTUNDODEBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODFBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODGBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
TEST_SETS                     TMTUNDODHBTT_APITAB_EFF_NUM_PLAINBTT_NUM_PASS
