
--
--  Install install_usr Scripts for UTP
--
--  The 2 scripts included are:
--    -) create_gusr
--    -) create_usyn
--


select ' -) create_gusr  ' as FILE_NAME from dual;


-- Script File "create_gusr"
--    Create GLobal User Synonyms

   -- Application: Unit Test Parameters
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   03, 2012  08:38:44 PM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- 
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- 
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 



create synonym glob
   for DTGEN_TEST.glob
/
create synonym util_log
   for DTGEN_TEST.util_log
/
create synonym util
   for DTGEN_TEST.util
/



select ' -) create_usyn  ' as FILE_NAME from dual;


-- Script File "create_usyn"
--    Create Synonyms for Users

   -- Application: Unit Test Parameters
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   03, 2012  08:38:49 PM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- 
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- 
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 



select '***  global_parms  ***' as TABLE_NAME from dual
/

--  Should use "global_parms_dml.get_next_id" instead of sequence
create synonym global_parms_seq
   for DTGEN_TEST.global_parms_seq
/
create synonym global_parms
   for DTGEN_TEST.global_parms
/
create synonym global_parms_dml
   for DTGEN_TEST.global_parms_dml
/
create synonym global_parms_act
   for DTGEN_TEST.global_parms_act
/

select '***  parm_sets  ***' as TABLE_NAME from dual
/

--  Should use "parm_sets_dml.get_next_id" instead of sequence
create synonym parm_sets_seq
   for DTGEN_TEST.parm_sets_seq
/
create synonym parm_sets
   for DTGEN_TEST.parm_sets
/
create synonym parm_sets_dml
   for DTGEN_TEST.parm_sets_dml
/
create synonym parm_sets_act
   for DTGEN_TEST.parm_sets_act
/

select '***  test_parms  ***' as TABLE_NAME from dual
/

--  Should use "test_parms_dml.get_next_id" instead of sequence
create synonym test_parms_seq
   for DTGEN_TEST.test_parms_seq
/
create synonym test_parms
   for DTGEN_TEST.test_parms
/
create synonym test_parms_dml
   for DTGEN_TEST.test_parms_dml
/
create synonym test_parms_act
   for DTGEN_TEST.test_parms_act
/

select '***  test_sets  ***' as TABLE_NAME from dual
/

--  Should use "test_sets_dml.get_next_id" instead of sequence
create synonym test_sets_seq
   for DTGEN_TEST.test_sets_seq
/
create synonym test_sets
   for DTGEN_TEST.test_sets
/
create synonym test_sets_dml
   for DTGEN_TEST.test_sets_dml
/
create synonym test_sets_act
   for DTGEN_TEST.test_sets_act
/



