create or replace view gui_app_tree_vw as
  select '' app
         ,'APP|' id
         ,'' par_id
         ,'APPLICATIONS' name
         ,'APP' abbr
         ,'Applications to be Generated by DTGen' description
         ,'ob_library.gif' icon
         ,'f?p=!APP_ID!:HOME:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P1_APP_ID:' ||
          'APP|,:' link
    from  dual
   union all
   select abbr app
         ,'APP|' || id id
         ,'APP|' par_id
         ,name
         ,abbr
         ,description
         ,'ob_library.gif' icon
         ,'f?p=!APP_ID!:HOME:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P1_APP_ID:' ||
          'APP|' || id || ',' || id ||
          ':' link
    from  applications_act
   union all
   select abbr app
         ,'TAB|' || abbr || '|' id
         ,'APP|' || id par_id
         ,'1) TABLES' name
         ,'TAB' abbr
         ,'Tables in Application ' || abbr description
         ,'pe_tabform.gif' icon
         ,'f?p=!APP_ID!:TABLES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_TAB_ID:' ||
          'TAB|' || abbr || '|,' ||
          ':' link
    from  applications_act
   union all
   select abbr app
         ,'DOM|' || abbr || '|' id
         ,'APP|' || id par_id
         ,'2) DOMAINS' name
         ,'DOM' abbr
         ,'Domains in Application ' || abbr description
         ,'pe_list.gif' icon
         ,'f?p=!APP_ID!:DOMAINS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P21_DOM_ID:' ||
          'DOM|' || abbr || '|,' ||
          ':' link
    from  applications_act
   union all
   select abbr app
         ,'PRG|' || abbr || '|' id
         ,'APP|' || id par_id
         ,'3) PROGRAMS' name
         ,'PRG' abbr
         ,'Programs in Application ' || abbr description
         ,'ob_package_body.gif' icon
         ,'f?p=!APP_ID!:PROGRAMS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P81_PRG_ID:' ||
          'PRG|' || abbr || '|,' ||
          ':' link
    from  applications_act
   union all
   select abbr app
         ,'EXC|' || abbr || '|' id
         ,'APP|' || id par_id
         ,'4) EXCEPTIONS' name
         ,'EXC' abbr
         ,'Exceptions in Application ' || abbr description
         ,'ob_trigger.gif' icon
         ,'f?p=!APP_ID!:EXCEPTIONS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P91_EXC_ID:' ||
          'EXC|' || abbr || '|,' ||
          ':' link
    from  applications_act
   union all
   select abbr app
         ,'F|' || abbr || '|' id
         ,'APP|' || id par_id
         ,'5) FILES' name
         ,'F' abbr
         ,'Files in Application ' || abbr description
         ,'pt_files.png' icon
         ,'f?p=!APP_ID!:FILES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P11_FILE_ID:' ||
          'F|' || abbr || '|,' ||
          ':' link
    from  applications_act
   union all
   select applications_nk1 app
         ,'GRP|' || applications_nk1 || '|' || nvl(group_name,' ') id
         ,'TAB|' || applications_nk1 || '|' par_id
         ,nvl(group_name,' ') || ' Table Group' name
         ,nvl(group_name,' ') abbr
         ,count(*)   || ' tables are included in the ' ||
          nvl(group_name,' ') || ' Table Group in Application ' ||
          applications_nk1         description
         ,'pt_list.png' icon
         ,'f?p=!APP_ID!:TABLES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_GROUP_NAME,P41_TAB_ID:' ||
          'TAB|' || applications_nk1 || '|' || nvl(group_name,' ') ||
          ',' || nvl(group_name,' ') || ',:' link
    from  tables_act
    group by applications_nk1
            ,application_id
            ,nvl(group_name,' ')
   union all
   select applications_nk1 app
         ,'TAB|' || applications_nk1 || '|' || id id
         ,'GRP|' || applications_nk1 || '|' || nvl(group_name,' ') par_id
         ,name
         ,abbr
         ,description
         ,'pe_tabform.gif' icon
         ,'f?p=!APP_ID!:TABLES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_GROUP_NAME,P41_TAB_ID:' ||
          'TAB|' || applications_nk1 || '|' || id ||
          ',' || nvl(group_name,' ') || ',' || id || ':' link
    from  tables_act
   union all
   select applications_nk1 app
         ,'COL|' || applications_nk1 || '|' || abbr || '|' id
         ,'TAB|' || applications_nk1 || '|' || id par_id
         ,'1) COLUMNS' name
         ,'COL' abbr
         ,'Columns in Table ' || abbr ||
          ' in Application ' || applications_nk1 description
         ,'ob_lob.gif' icon
         ,'f?p=!APP_ID!:TAB_COLS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_TABLES_NK2,P51_COL_ID:' ||
          'COL|' || applications_nk1 || '|' || abbr || '|,' ||
          abbr || ',:' link
    from  tables_act
   union all
   select applications_nk1 app
         ,'CON|' || applications_nk1 || '|' || abbr || '|' id
         ,'TAB|' || applications_nk1 || '|' || id par_id
         ,'2) CONSTRAINTS' name
         ,'CON' abbr
         ,'Constraints on Table ' || abbr ||
          ' in Application ' || applications_nk1 description
         ,'ob_browser.gif' icon
         ,'f?p=!APP_ID!:CHECK_CONS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_TABLES_NK2,P61_CON_ID:' ||
          'CON|' || applications_nk1 || '|' || abbr || '|,' ||
          abbr || ',:' link
    from  tables_act
   union all
   select applications_nk1 app
         ,'IND|' || applications_nk1 || '|' || abbr || '|' id
         ,'TAB|' || applications_nk1 || '|' || id par_id
         ,'3) INDEXES' name
         ,'IND' abbr
         ,'Indexes on Table ' || abbr ||
          ' in Application '  || applications_nk1 description
         ,'ob_index.gif' icon
         ,'f?p=!APP_ID!:TAB_INDEXES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_TABLES_NK2,P71_IND_TAG:' ||
          'IND|' || applications_nk1 || '|' || abbr || '|,' ||
          abbr || ',:' link
    from  tables_act
   union all
   select tc.tables_nk1 app
         ,'COL|' || tc.tables_nk1 || '|' || tc.tables_nk2 || '|' || tc.id id
         ,'COL|' || tc.tables_nk1 || '|' || tc.tables_nk2 || '|' par_id
         ,tc.name || '  '
         || nvl2(tc.fk_tables_nk2,'FK:'||fk.name,'')
         || nvl2(tc.d_domains_nk2,'DOM:'||d.name,'')
         || nvl2(tc.type,lower(tc.type)
                        || nvl2(tc.len,'(' || tc.len
                                      || nvl2(tc.scale,'.'||tc.scale,'')
                                      || ')'
                                      ,'')
                        ,'')   name
         ,trim(to_char(tc.seq)) abbr
         ,tc.description
         ,'ob_lob.gif' icon
         ,'f?p=!APP_ID!:TAB_COLS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_TABLES_NK2,P51_COL_ID:' ||
          'COL|' || tc.tables_nk1 || '|' || tc.tables_nk2 || '|' || tc.id ||
          ',' || tc.tables_nk2 || ',' || tc.id || ':' link
    from  tab_cols_act tc
          left outer join tables_act fk on tc.fk_table_id = fk.id
          left outer join domains_act d on tc.d_domain_id =  d.id
   union all
   select tables_nk1 app
         ,'CON|' || tables_nk1 || '|' || tables_nk2 || '|' || id id
         ,'CON|' || tables_nk1 || '|' || tables_nk2 || '|' par_id
         ,text name
         ,trim(to_char(seq)) abbr
         ,description
         ,'ob_browser.gif' icon
         ,'f?p=!APP_ID!:CHECK_CONS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_TABLES_NK2,P61_CON_ID:' ||
          'CON|' || tables_nk1 || '|' || tables_nk2 || '|' || id ||
          ',' || tables_nk2 || ',' || id || ':' link
    from  check_cons_act
   union all
   select i.tab_cols_nk1 app
         ,'IND|' || i.tab_cols_nk1 || '|' || i.tab_cols_nk2 || '|' || i.tag id
         ,'IND|' || i.tab_cols_nk1 || '|' || i.tab_cols_nk2 || '|' par_id
         ,t.name || '_' || i.tag || case substr(i.tag,1,1)
                                    when 'u' then ' (Unique)'
                                    end                       name
         ,t.abbr || '_' || i.tag abbr
         ,gui_util.index_desc (i.tab_cols_nk1, i.tab_cols_nk2, i.tag) description
         ,'ob_index.gif' icon
         ,'f?p=!APP_ID!:TAB_INDEXES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P41_TABLES_NK2,P71_IND_TAG:' ||
          'IND|' || i.tab_cols_nk1 || '|' || i.tab_cols_nk2 || '|' || i.tag ||
          ',' || i.tab_cols_nk2 || ',' || i.tag || ':' link
    from  tab_inds_act i
          inner join tab_cols tc on i.tab_col_id = tc.id
          inner join tables t    on tc.table_id  = t.id
    group by i.tab_cols_nk1
            ,i.tab_cols_nk2
            ,tc.table_id
            ,t.name
            ,t.abbr
            ,i.tag
   union all
   select applications_nk1 app
         ,'PRG|' || applications_nk1 || '|' || id id
         ,'PRG|' || applications_nk1 || '|' par_id
         ,name
         ,'' abbr
         ,description
         ,'ob_package_body.gif' icon
         ,'f?p=!APP_ID!:PROGRAMS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P81_PRG_ID:' ||
          'PRG|' || applications_nk1 || '|' || id || ',' || id ||
          ':' link
    from  programs_act
   union all
   select applications_nk1 app
         ,'DOM|' || applications_nk1 || '|' || id id
         ,'DOM|' || applications_nk1 || '|' par_id
         ,name
         ,abbr
         ,description
         ,'pe_list.gif' icon
         ,'f?p=!APP_ID!:DOMAINS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P21_DOM_ID:' ||
          'DOM|' || applications_nk1 || '|' || id ||
          ',' || id || ':' link
    from  domains_act
   union all
   select domains_nk1 app
         ,'VAL|' || domains_nk1 || '|' || domains_nk2 || '|' || id id
         ,'DOM|' || domains_nk1 || '|' || domain_id par_id
         ,value name
         ,'' || seq abbr
         ,description
         ,'pe_list.gif' icon
         ,'f?p=!APP_ID!:DOMAIN_VALUES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P21_DOMAINS_NK2,P31_VAL_ID:' ||
          'VAL|' || domains_nk1 || '|' || domains_nk2 || '|' || id ||
          ',' || domains_nk2 || ',' || id || ':' link
    from  domain_values_act
   union all
   select applications_nk1 app
         ,'EXC|' || applications_nk1 || '|' || id id
         ,'EXC|' || applications_nk1 || '|' par_id
         ,name
         ,'' || code abbr
         ,message description
         ,'ob_trigger.gif' icon
         ,'f?p=!APP_ID!:EXCEPTIONS:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P91_EXC_ID:' ||
          'EXC|' || applications_nk1 || '|' || id ||
          ',' || id || ':' link
    from  exceptions_act
   union all
   select applications_nk1 app
         ,'F|' || applications_nk1 || '|' || id id
         ,'F|' || applications_nk1 || '|' par_id
         ,name
         ,'' abbr
         ,description description
         ,'ob_trigger.gif' icon
         ,'f?p=!APP_ID!:FILES:!APP_SESSION!::!DEBUG!::' ||
          'P1_TREE_ID,P11_FILE_ID:' ||
          'F|' || applications_nk1 || '|' || id ||
          ',' || id || ':' link
    from  files_act;
