
--
--  Install install_db Security Scripts for DTGEN
--
--  The 6 scripts included are:
--    -) create_glob_sec
--    -) create_ods_sec
--    -) create_integ_sec
--    -) create_oltp_sec
--    -) create_aa_sec
--    -) create_mods_sec
--


select ' -) create_glob_sec  ' as FILE_NAME from dual;


-- Script File "create_glob_sec"
--    Security script to Create Globals using generated code

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   08, 2012  12:15:52 PM














grant execute on glob to DTGEN_app
/
---- audit rename on glob by access
---- /

grant execute on pair_type to DTGEN_dml
/
---- audit rename on pair_type by access
---- /

grant execute on col_type to DTGEN_dml
/
---- audit rename on col_type by access
---- /

grant insert on util_log to DTGEN_app
/
-- grant update on util_log to DTGEN_app
-- /
grant delete on util_log to DTGEN_app
/
grant select on util_log to DTGEN_app
/
-- audit rename on util_log by access
-- /

grant execute on util to DTGEN_app
/
---- audit rename on util by access
---- /



select ' -) create_ods_sec  ' as FILE_NAME from dual;


-- Script File "create_ods_sec"
--    Security script to Create Online Data Store using generated code

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   08, 2012  12:15:52 PM



grant execute on applications_tab to DTGEN_dml
/
---- audit rename on applications_tab by access;
---- /

grant alter on applications_seq to DTGEN_dml
/
grant select on applications_seq to DTGEN_app
/
-- audit rename on applications_seq by access
-- /

grant select on applications to DTGEN_app
/
grant insert on applications to DTGEN_dml
/
grant update on applications to DTGEN_dml
/
grant delete on applications to DTGEN_dml
/
-- audit rename on applications by access
-- /

grant execute on files_pop to DTGEN_app
/
---- audit rename on files_pop by access
---- /

grant execute on files_tab to DTGEN_dml
/
---- audit rename on files_tab by access;
---- /

grant alter on files_seq to DTGEN_dml
/
grant select on files_seq to DTGEN_app
/
-- audit rename on files_seq by access
-- /

grant select on files to DTGEN_app
/
grant insert on files to DTGEN_dml
/
grant update on files to DTGEN_dml
/
grant delete on files to DTGEN_dml
/
-- audit rename on files by access
-- /

grant select on files_AUD to DTGEN_app
/
grant insert on files_AUD to DTGEN_dml
/
-- grant update on files_AUD to DTGEN_dml
-- /
grant delete on files_AUD to DTGEN_dml
/
-- audit rename on files_AUD by access
-- /

grant select on files_PDAT to DTGEN_app
/
grant insert on files_PDAT to DTGEN_dml
/
-- grant update on files_PDAT to DTGEN_dml
-- /
grant delete on files_PDAT to DTGEN_dml
/
-- audit rename on files_PDAT by access
-- /

grant execute on file_lines_pop to DTGEN_app
/
---- audit rename on file_lines_pop by access
---- /

grant execute on file_lines_tab to DTGEN_dml
/
---- audit rename on file_lines_tab by access;
---- /

grant alter on file_lines_seq to DTGEN_dml
/
grant select on file_lines_seq to DTGEN_app
/
-- audit rename on file_lines_seq by access
-- /

grant select on file_lines to DTGEN_app
/
grant insert on file_lines to DTGEN_dml
/
grant update on file_lines to DTGEN_dml
/
grant delete on file_lines to DTGEN_dml
/
-- audit rename on file_lines by access
-- /

grant select on file_lines_AUD to DTGEN_app
/
grant insert on file_lines_AUD to DTGEN_dml
/
-- grant update on file_lines_AUD to DTGEN_dml
-- /
grant delete on file_lines_AUD to DTGEN_dml
/
-- audit rename on file_lines_AUD by access
-- /

grant select on file_lines_PDAT to DTGEN_app
/
grant insert on file_lines_PDAT to DTGEN_dml
/
-- grant update on file_lines_PDAT to DTGEN_dml
-- /
grant delete on file_lines_PDAT to DTGEN_dml
/
-- audit rename on file_lines_PDAT by access
-- /

grant execute on domains_tab to DTGEN_dml
/
---- audit rename on domains_tab by access;
---- /

grant alter on domains_seq to DTGEN_dml
/
grant select on domains_seq to DTGEN_app
/
-- audit rename on domains_seq by access
-- /

grant select on domains to DTGEN_app
/
grant insert on domains to DTGEN_dml
/
grant update on domains to DTGEN_dml
/
grant delete on domains to DTGEN_dml
/
-- audit rename on domains by access
-- /

grant execute on domain_values_tab to DTGEN_dml
/
---- audit rename on domain_values_tab by access;
---- /

grant alter on domain_values_seq to DTGEN_dml
/
grant select on domain_values_seq to DTGEN_app
/
-- audit rename on domain_values_seq by access
-- /

grant select on domain_values to DTGEN_app
/
grant insert on domain_values to DTGEN_dml
/
grant update on domain_values to DTGEN_dml
/
grant delete on domain_values to DTGEN_dml
/
-- audit rename on domain_values by access
-- /

grant execute on tables_tab to DTGEN_dml
/
---- audit rename on tables_tab by access;
---- /

grant alter on tables_seq to DTGEN_dml
/
grant select on tables_seq to DTGEN_app
/
-- audit rename on tables_seq by access
-- /

grant select on tables to DTGEN_app
/
grant insert on tables to DTGEN_dml
/
grant update on tables to DTGEN_dml
/
grant delete on tables to DTGEN_dml
/
-- audit rename on tables by access
-- /

grant execute on tab_cols_tab to DTGEN_dml
/
---- audit rename on tab_cols_tab by access;
---- /

grant alter on tab_cols_seq to DTGEN_dml
/
grant select on tab_cols_seq to DTGEN_app
/
-- audit rename on tab_cols_seq by access
-- /

grant select on tab_cols to DTGEN_app
/
grant insert on tab_cols to DTGEN_dml
/
grant update on tab_cols to DTGEN_dml
/
grant delete on tab_cols to DTGEN_dml
/
-- audit rename on tab_cols by access
-- /

grant execute on tab_inds_tab to DTGEN_dml
/
---- audit rename on tab_inds_tab by access;
---- /

grant alter on tab_inds_seq to DTGEN_dml
/
grant select on tab_inds_seq to DTGEN_app
/
-- audit rename on tab_inds_seq by access
-- /

grant select on tab_inds to DTGEN_app
/
grant insert on tab_inds to DTGEN_dml
/
grant update on tab_inds to DTGEN_dml
/
grant delete on tab_inds to DTGEN_dml
/
-- audit rename on tab_inds by access
-- /

grant execute on check_cons_tab to DTGEN_dml
/
---- audit rename on check_cons_tab by access;
---- /

grant alter on check_cons_seq to DTGEN_dml
/
grant select on check_cons_seq to DTGEN_app
/
-- audit rename on check_cons_seq by access
-- /

grant select on check_cons to DTGEN_app
/
grant insert on check_cons to DTGEN_dml
/
grant update on check_cons to DTGEN_dml
/
grant delete on check_cons to DTGEN_dml
/
-- audit rename on check_cons by access
-- /

grant execute on programs_tab to DTGEN_dml
/
---- audit rename on programs_tab by access;
---- /

grant alter on programs_seq to DTGEN_dml
/
grant select on programs_seq to DTGEN_app
/
-- audit rename on programs_seq by access
-- /

grant select on programs to DTGEN_app
/
grant insert on programs to DTGEN_dml
/
grant update on programs to DTGEN_dml
/
grant delete on programs to DTGEN_dml
/
-- audit rename on programs by access
-- /

grant execute on exceptions_tab to DTGEN_dml
/
---- audit rename on exceptions_tab by access;
---- /

grant alter on exceptions_seq to DTGEN_dml
/
grant select on exceptions_seq to DTGEN_app
/
-- audit rename on exceptions_seq by access
-- /

grant select on exceptions to DTGEN_app
/
grant insert on exceptions to DTGEN_dml
/
grant update on exceptions to DTGEN_dml
/
grant delete on exceptions to DTGEN_dml
/
-- audit rename on exceptions by access
-- /



select ' -) create_integ_sec  ' as FILE_NAME from dual;


-- Script File "create_integ_sec"
--    Security script to Create ODS integrity using generated code

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   08, 2012  12:15:52 PM





select ' -) create_oltp_sec  ' as FILE_NAME from dual;


-- Script File "create_oltp_sec"
--    Security script to Create Online Transaction Processing using generated code

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   08, 2012  12:15:53 PM



grant execute on applications_view to DTGEN_dml
/
---- audit rename on applications_view by access
---- /

grant select on applications_act to DTGEN_app
/
grant insert on applications_act to DTGEN_app
/
grant update on applications_act to DTGEN_app
/
grant delete on applications_act to DTGEN_app
/
-- audit rename on applications_act by access
-- /

grant execute on applications_dml to DTGEN_app
/
---- audit rename on applications_dml by access
---- /

grant execute on files_view to DTGEN_dml
/
---- audit rename on files_view by access
---- /

grant select on files_act to DTGEN_app
/
grant insert on files_act to DTGEN_app
/
grant update on files_act to DTGEN_app
/
grant delete on files_act to DTGEN_app
/
-- audit rename on files_act by access
-- /

grant execute on files_dml to DTGEN_app
/
---- audit rename on files_dml by access
---- /

grant execute on file_lines_view to DTGEN_dml
/
---- audit rename on file_lines_view by access
---- /

grant select on file_lines_act to DTGEN_app
/
grant insert on file_lines_act to DTGEN_app
/
grant update on file_lines_act to DTGEN_app
/
grant delete on file_lines_act to DTGEN_app
/
-- audit rename on file_lines_act by access
-- /

grant execute on file_lines_dml to DTGEN_app
/
---- audit rename on file_lines_dml by access
---- /

grant execute on domains_view to DTGEN_dml
/
---- audit rename on domains_view by access
---- /

grant select on domains_act to DTGEN_app
/
grant insert on domains_act to DTGEN_app
/
grant update on domains_act to DTGEN_app
/
grant delete on domains_act to DTGEN_app
/
-- audit rename on domains_act by access
-- /

grant execute on domains_dml to DTGEN_app
/
---- audit rename on domains_dml by access
---- /

grant execute on domain_values_view to DTGEN_dml
/
---- audit rename on domain_values_view by access
---- /

grant select on domain_values_act to DTGEN_app
/
grant insert on domain_values_act to DTGEN_app
/
grant update on domain_values_act to DTGEN_app
/
grant delete on domain_values_act to DTGEN_app
/
-- audit rename on domain_values_act by access
-- /

grant execute on domain_values_dml to DTGEN_app
/
---- audit rename on domain_values_dml by access
---- /

grant execute on tables_view to DTGEN_dml
/
---- audit rename on tables_view by access
---- /

grant select on tables_act to DTGEN_app
/
grant insert on tables_act to DTGEN_app
/
grant update on tables_act to DTGEN_app
/
grant delete on tables_act to DTGEN_app
/
-- audit rename on tables_act by access
-- /

grant execute on tables_dml to DTGEN_app
/
---- audit rename on tables_dml by access
---- /

grant execute on tab_cols_view to DTGEN_dml
/
---- audit rename on tab_cols_view by access
---- /

grant select on tab_cols_act to DTGEN_app
/
grant insert on tab_cols_act to DTGEN_app
/
grant update on tab_cols_act to DTGEN_app
/
grant delete on tab_cols_act to DTGEN_app
/
-- audit rename on tab_cols_act by access
-- /

grant execute on tab_cols_dml to DTGEN_app
/
---- audit rename on tab_cols_dml by access
---- /

grant execute on tab_inds_view to DTGEN_dml
/
---- audit rename on tab_inds_view by access
---- /

grant select on tab_inds_act to DTGEN_app
/
grant insert on tab_inds_act to DTGEN_app
/
grant update on tab_inds_act to DTGEN_app
/
grant delete on tab_inds_act to DTGEN_app
/
-- audit rename on tab_inds_act by access
-- /

grant execute on tab_inds_dml to DTGEN_app
/
---- audit rename on tab_inds_dml by access
---- /

grant execute on check_cons_view to DTGEN_dml
/
---- audit rename on check_cons_view by access
---- /

grant select on check_cons_act to DTGEN_app
/
grant insert on check_cons_act to DTGEN_app
/
grant update on check_cons_act to DTGEN_app
/
grant delete on check_cons_act to DTGEN_app
/
-- audit rename on check_cons_act by access
-- /

grant execute on check_cons_dml to DTGEN_app
/
---- audit rename on check_cons_dml by access
---- /

grant execute on programs_view to DTGEN_dml
/
---- audit rename on programs_view by access
---- /

grant select on programs_act to DTGEN_app
/
grant insert on programs_act to DTGEN_app
/
grant update on programs_act to DTGEN_app
/
grant delete on programs_act to DTGEN_app
/
-- audit rename on programs_act by access
-- /

grant execute on programs_dml to DTGEN_app
/
---- audit rename on programs_dml by access
---- /

grant execute on exceptions_view to DTGEN_dml
/
---- audit rename on exceptions_view by access
---- /

grant select on exceptions_act to DTGEN_app
/
grant insert on exceptions_act to DTGEN_app
/
grant update on exceptions_act to DTGEN_app
/
grant delete on exceptions_act to DTGEN_app
/
-- audit rename on exceptions_act by access
-- /

grant execute on exceptions_dml to DTGEN_app
/
---- audit rename on exceptions_dml by access
---- /



select ' -) create_aa_sec  ' as FILE_NAME from dual;


-- Script File "create_aa_sec"
--    Security script to Create _ALL and _ASOF Views and Package

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   08, 2012  12:15:52 PM



grant select on files_all to DTGEN_app
/
-- audit rename on files_all by access
-- /

grant select on files_asof to DTGEN_app
/
-- audit rename on files_asof by access
-- /

grant select on file_lines_all to DTGEN_app
/
-- audit rename on file_lines_all by access
-- /

grant select on file_lines_asof to DTGEN_app
/
-- audit rename on file_lines_asof by access
-- /



select ' -) create_mods_sec  ' as FILE_NAME from dual;


-- Script File "create_mods_sec"
--    Security script to Create Program Modules

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   08, 2012  12:15:53 PM



grant execute on dtgen_util to DTGEN_app
/
---- audit rename on dtgen_util by access
---- /

grant execute on generate to DTGEN_app
/
---- audit rename on generate by access
---- /


