
--
--  Uninstall uninstall_usr Scripts for DTGEN
--
--  The 2 scripts included are:
--    -) drop_usyn
--    -) drop_gusr
--


select ' -) drop_usyn  ' as FILE_NAME from dual;


-- Script File "drop_usyn"
--    Drop Synonyms for Users

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   04, 2012  09:54:24 AM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 



drop synonym generate
/
drop synonym dtgen_util
/

select '***  exceptions  ***' as TABLE_NAME from dual
/
drop synonym exceptions_act
/
drop synonym exceptions_dml
/
drop synonym exceptions
/
drop synonym exceptions_seq
/

select '***  programs  ***' as TABLE_NAME from dual
/
drop synonym programs_act
/
drop synonym programs_dml
/
drop synonym programs
/
drop synonym programs_seq
/

select '***  check_cons  ***' as TABLE_NAME from dual
/
drop synonym check_cons_act
/
drop synonym check_cons_dml
/
drop synonym check_cons
/
drop synonym check_cons_seq
/

select '***  tab_inds  ***' as TABLE_NAME from dual
/
drop synonym tab_inds_act
/
drop synonym tab_inds_dml
/
drop synonym tab_inds
/
drop synonym tab_inds_seq
/

select '***  tab_cols  ***' as TABLE_NAME from dual
/
drop synonym tab_cols_act
/
drop synonym tab_cols_dml
/
drop synonym tab_cols
/
drop synonym tab_cols_seq
/

select '***  tables  ***' as TABLE_NAME from dual
/
drop synonym tables_act
/
drop synonym tables_dml
/
drop synonym tables
/
drop synonym tables_seq
/

select '***  domain_values  ***' as TABLE_NAME from dual
/
drop synonym domain_values_act
/
drop synonym domain_values_dml
/
drop synonym domain_values
/
drop synonym domain_values_seq
/

select '***  domains  ***' as TABLE_NAME from dual
/
drop synonym domains_act
/
drop synonym domains_dml
/
drop synonym domains
/
drop synonym domains_seq
/

select '***  file_lines  ***' as TABLE_NAME from dual
/
drop synonym file_lines_asof
/
drop synonym file_lines_all
/
drop synonym file_lines_act
/
drop synonym file_lines_dml
/
drop synonym file_lines_pop
/
drop synonym file_lines_PDAT
/
drop synonym file_lines_AUD
/
drop synonym file_lines
/
drop synonym file_lines_seq
/

select '***  files  ***' as TABLE_NAME from dual
/
drop synonym files_asof
/
drop synonym files_all
/
drop synonym files_act
/
drop synonym files_dml
/
drop synonym files_pop
/
drop synonym files_PDAT
/
drop synonym files_AUD
/
drop synonym files
/
drop synonym files_seq
/

select '***  applications  ***' as TABLE_NAME from dual
/
drop synonym applications_act
/
drop synonym applications_dml
/
drop synonym applications
/
drop synonym applications_seq
/



select ' -) drop_gusr  ' as FILE_NAME from dual;


-- Script File "drop_gusr"
--    Drop Global User Synonyms

   -- Application: Dtgen For Oracle
   -- Generated by DTGen (http://code.google.com/p/dtgen)
   -- October   04, 2012  09:54:27 AM

   --
   -- Copyright (c) 2012, Duane.Dieterich@gmail.com
   -- All rights reserved.
   -- 
   -- Redistribution and use in source and binary forms, with or without 
   -- modification, are permitted provided that the following conditions are 
   -- met:
   -- 
   -- Redistributions of source code must retain the above copyright notice, 
   -- this list of conditions and the following disclaimer.
   -- Redistributions in binary form must reproduce the above copyright notice, 
   -- this list of conditions and the following disclaimer in the documentation 
   -- and/or other materials provided with the distribution.
   -- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
   -- IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
   -- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
   -- PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
   -- CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
   -- EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
   -- PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
   -- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
   -- LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
   -- NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
   -- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -- 



drop synonym util
/
drop synonym util_log
/
drop synonym glob
/


